displayName: Query Token Authentication
type: middleware
import: github.com/flohoss/token-auth
summary: Query-Token authentication middleware
testData:
  tokenParam: token
  cookieName: auth_session
  maxRateLimitEntries: 10000
  allowedTokens:
    - secret-token-1
    - secret-token-2
